In [2]:
# numpy.ndarray 클래스
# 동일한 자료형을 가지는 값들이 배열 형태로 존재함.
# N차원 형태로 구성이 가능
# 각 값들은 양의 정수인 색인(index)이 부여되어 있다.
# numpy에서 차원(dimension)을 rank, axis라고 부르기도 한다.
# ndarray를 줄여서 array로 표현한다.

### 라이브러리 불러오기

In [3]:
import numpy as np
# numpy를 np라고 칭하겠다.

### 1차원 배열(array) 만들기

In [4]:
# array() - 다양한 값을 ndarray로 반환
list1 = [1,2,3,4,5]
arr = np.array(list1) # numpy에서 list1 만들어줘
arr

array([1, 2, 3, 4, 5])

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
# 2차원 array 생성
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

### 배열의 크기 확인

In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# shape = 배열의 크기 (행, 열)
# 1차원 -> shape:(4,), 2차원 -> shape:(2, 3), 3차원 -> shape:(4, 3, 2)
arr2.shape

(2, 3)

In [9]:
# size = 배열 전체 요소의 개수
arr2.size

6

In [10]:
# ndim = 배열의 차원
arr2.ndim

2

In [17]:
list2 = [[[1,2],[3,4]],
        [[5,6],[7,8]]]

In [18]:
list2

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [19]:
arr3 = np.array(list2)

In [20]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
print('배열의 크기 :', arr3.shape)
print('배열의 차원 :', arr3.ndim)
print('배열의 개수 :', arr3.size)

배열의 크기 : (2, 2, 2)
배열의 차원 : 3
배열의 개수 : 8


### array 생성

In [23]:
# 특정한 값으로 배열 생성하기
# np.zeros((행, 열)) -> 0으로 이루어진 배열 생성
# 기본적으로 실수형으로 만들어진다.(즉, 소수)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
# dtype = '데이터타입', int = '정수'
np.zeros((3,4),dtype='int') # -> 정수로 생성하고 싶을 때 데이터타입 변경

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
# np.ones((행, 열)) -> 1으로 이루어진 배열 생성
# 기본적으로 실수형으로 만들어진다.(즉, 소수)
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.ones((2,3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

In [28]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [29]:
# 원하는 값으로 배열을 채워주는 함수
# np.full((행, 열), 원하는 값)
# 숫자에 .이 안찍히는 이유는 원하는 값이 int값(정수)이기 때문
np.full((5,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [31]:
# 데이터 타입을 float로 바꾸면 다시 실수로 바뀜
np.full((5,5),3,dtype='float')

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [35]:
# 1 ~ 50이 담긴 리스트 생성
list1 = []
for i in range(1,51):
    list1.append(i)
print(list1, end=' ')

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50] 

In [36]:
np.array(list1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [40]:
# np.arange() -> 배열의 형태로 범위 지정해주는 함수 (0부터 시작)
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [41]:
np.arange(1,51)
# for - range -> 복잡한 for문
#    'a'range -> np에선 간단한 array 배열로 만들어준다

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

### 랜덤 값 배열 생성하기

In [42]:
# 랜덤 값으로 이루어진 배열 생성 (1)
# 0 ~ 1 사이 실수 값 생성
arr_ran = np.random.rand(2,3)
arr_ran

array([[0.60274041, 0.84682762, 0.89980213],
       [0.86243003, 0.68198518, 0.31970955]])

In [43]:
# 랜덤 값으로 이루어진 배열 생성 (2)
# (시작, 끝-1) 사이의 랜덤한 정수 1개 생성
arr_ran2 = np.random.randint(2,10)
arr_ran2

5

In [45]:
# (시작, 끝-1) 사이의 랜덤한 정수, 원하는 크기의 배열 생성
arr_ran3 = np.random.randint(2,10, size=(2,3))
arr_ran3

array([[7, 3, 6],
       [8, 8, 4]])

In [46]:
# 타입 지정하여 배열 생성
arr_type = np.array([1.2,2.3,3.4], dtype='int')
arr_type

array([1, 2, 3])

In [47]:
# astype() -> 배열 타입 변경해주는 함수
arr_type.astype('float')

array([1., 2., 3.])

### array 연산

In [50]:
# 파이썬 리스트 연산 (값은 자리의 값 연산 실습)
list1 = [1,2,3]
list2 = [4,5,6]
list1 + list2

[1, 2, 3, 4, 5, 6]

In [53]:
list3 = []
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])
list3

[5, 7, 9]

In [54]:
# 파이썬 리스트를 배열로
arr1 = np.array(list1)
arr2 = np.array(list2)

In [55]:
arr1

array([1, 2, 3])

In [56]:
arr2

array([4, 5, 6])

In [57]:
# numpy.array 연산
# array 연산은 기본적으로 요소별 연산이 진행됨
# 반복문 필요 없이 같은 자리의 값끼리 연산 가능
arr1 + arr2

array([5, 7, 9])

### 배열 인덱싱, 슬라이싱

#### 인덱싱

In [60]:
arr= np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
# 특정 행 인덱싱
arr[0]

array([1, 2, 3])

In [62]:
# 특정 행, 특정 열 인덱싱 (1)
arr[0][0]

1

In [63]:
# 특정 행, 특정 열 인덱싱 (2)
arr[0,0]

1

In [65]:
arr[0,2]

3

#### 슬라이싱

In [68]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [71]:
# 1차원 배열 슬라이싱
# (시작, 끝 -1) 범위의 값 슬라이싱
arr1[3:8]

array([3, 4, 5, 6, 7])

In [78]:
# 2차원 배열 슬라이싱
# 0 ~ 50까지의 범위 배열로 만들기
# reshape() -> 배열의 크기를 다시 지정
# 원래 배열의 요소 개수와 바뀔 배열의 요소 개수가 같아야 한다.
arr2 = np.arange(1,51).reshape(5,10)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [79]:
# 2차원 배열 슬라이싱
# 슬라이싱할 범위 지정 ' : '
# [행의 범위, 열의 범위]
# [ :값] -> 처음부터 값 전까지
# [값: ] -> 값부터 끝까지
# [ : ] -> 처음부터 끝까지
arr2[:2,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [80]:
arr2[:,:2]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42]])

In [83]:
arr2[1:4,:5]

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [85]:
arr2[[2,3]]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [88]:
# ',' 콤마를 기준으로 행, 열
# 2행 1열, 3행 2열의 데이터
#     ↓행자리
arr2[[2,3],[1,2]]
#           ↑열자리

array([22, 33])

In [91]:
arr2[[3,4],[3,4]]

array([34, 45])

### BMI 구하기 

In [97]:
# np.load_txt("파일명.확장자", 구분문자) -> numpy 파일을 불러오는 함수
# delimiter -> 구분 기호
data = np.loadtxt("height_weight.txt", delimiter=',')
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [101]:
height = data[0] / 100 # <- bmi지수는 키를 미터단위로 계산, (cm -> m)
weight = data[1]

In [102]:
print(height)
print(weight)

[1.752 1.803 1.75  1.692 1.852 1.88  1.776 1.782 1.77  1.79 ]
[65.6 88.  79.2 69.3 55.  71.2 73.  68.9 74.  82. ]


In [110]:
bmi = weight / (height**2) # ** <- 제곱연산
print(bmi)

[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]


### Boolean 인덱싱 
- Boolean : True / False
- True 값 출력
- False 값은 출력하지 않음

In [3]:
import numpy as np

In [4]:
num = np.random.randint(50,101,size=6)
num

array([78, 89, 82, 61, 81, 92])

In [5]:
num >= 70 # boolean

array([ True,  True,  True, False,  True,  True])

In [6]:
# 변수명[인덱스위치]
# 불리언 인덱싱
# 변수명[조건]
num[num <= 70]

array([61])

In [8]:
name = np.array(['세연','지연','동현','누리'],dtype='<U2')
name

array(['세연', '지연', '동현', '누리'], dtype='<U2')

In [9]:
bol = np.array([True, False, True, False])
bol

array([ True, False,  True, False])

In [10]:
# True 위치에 해당하는 결과 값만 반환
name[bol]

array(['세연', '동현'], dtype='<U2')

In [18]:
# 데이터 생성
name_score = np.array([['세연',100],
          ['동현', 80],
          ['명훈', 30],
          ['경성', 50]])
name_score

array([['세연', '100'],
       ['동현', '80'],
       ['명훈', '30'],
       ['경성', '50']], dtype='<U3')

In [19]:
# 이름 값만 슬라이싱 하기
# [행,열]
name_score[:,0]

array(['세연', '동현', '명훈', '경성'], dtype='<U3')

In [25]:
name_score[:,0] == '세연'

array([ True, False, False, False])

In [26]:
# 위치를 알기 힘들다 -> 조건 필터링을 해보자!
name_score[name_score[:,0] == '세연']
# name_score[0] -> 위치에 따라서 인덱싱
# U3 -> 유니코드3

array([['세연', '100']], dtype='<U3')

In [27]:
name_score[0]

array(['세연', '100'], dtype='<U3')

### numpy 다양한 함수들
- sum : 합계
- mean : 평균
- abs : 절대값

In [33]:
# 1 ~ 10까지가 담긴 1차원 배열 생성 : arange()
arr = np.arange(1,11)
# 위의 배열을 (2,5) 크기로 바꿔주기 : reshape()
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
# np.sum() -> 합계
#  요소 전체 더하기
print(np.sum(arr))
print(arr.sum())

55
55


In [41]:
# 축 방향. axis=0 -> 행이 길어지는 방향으로 더하기 (위에서 아래로)
# 열 방향. axis=1 -> 열이 길어지는 방향 (좌에서 우로)
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[ 7  9 11 13 15]
[15 40]


In [38]:
# np.mean() - > 평균
# 요소 전체 평균
print(np.mean(arr))
print(arr.mean())

5.5
5.5


In [42]:
# np.abs() - > 절댓값
arr2 = np.array([1, -2, 3, -4, 5])
arr2

array([ 1, -2,  3, -4,  5])

In [43]:
np.abs(arr2)

array([1, 2, 3, 4, 5])

In [44]:
### '달러'를 '원'단위로 환산
dollar= np.array([12, 5, 30, 4, 10])
dollar

array([12,  5, 30,  4, 10])

In [45]:
# 환율이 1200
won = dollar*1200
won

array([14400,  6000, 36000,  4800, 12000])