In [1]:
import numpy as np

In [3]:
# np.loadtxt('파일명.확장자', 파일에서 사용한 구분 문자, 데이터 타입 지정)
# delimiter -> 구분 문자
data = np.loadtxt('ratings.txt', delimiter='::', dtype = 'int')
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [6]:
# 데이터 구조 확인하기
# 크기, 요소의 개수, 차원
print('크기 :', data.shape)
print('요소의 개수 :', data.size)
print('차원 :', data.ndim)

크기 : (1000209, 4)
요소의 개수 : 4000836
차원 : 2


### 1번 user 전체 정보 출력

In [9]:
# 1. id 정보만 가져오기
data[:,0]

array([   1,    1,    1, ..., 6040, 6040, 6040])

In [10]:
# 2. id가 1인 데이터만 가져오기
#     ↑조건 (불리언인덱싱)
data[:,0] == 1

array([ True,  True,  True, ..., False, False, False])

In [12]:
# 3. 불리언인덱싱
data[data[:,0]==1]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

### 전체 사용자의 평점 평균 구하기

In [15]:
# 1. 평점 데이터만 인덱싱
data[:,2]

array([5, 3, 3, ..., 5, 4, 4])

In [17]:
# 2. 평점 데이터 평균값 -> mean()
np.mean(data[:,2])

3.581564453029317

### 1번 사용자의 평점 평균 구하기

In [24]:
# 1번 + 2번 문제

# 1. 1번 사용자의 전체 데이터 구하기
user_1 = data[data[:,0]==1]
# 2. 1번 사용자의 전체 데이터에서 평점 가져오기
ratings_1 = user_1[:,2]
# 3. 가져온 평점에서 평균을 구하기
np.mean(ratings_1)

4.188679245283019

### 4. 각 사용자의 평점 평균 구하기

In [39]:
# 데이터의 중복을 제거하고 출력
# np.unique
user_id = np.unique(data[:,0])
user_id

array([   1,    2,    3, ..., 6038, 6039, 6040])

In [40]:
data[:,0]

array([   1,    1,    1, ..., 6040, 6040, 6040])

In [43]:
# 사용자별 평점 평균을 구하는 for문 만들기
user_id = np.unique(data[:,0])
list1 = []
# 1. 반복문 사용
for user in user_id:
    # 2. id 정보 가져오기
    u_id = data[:,0]
    # 3. 사용자별 정보 가져오기 (불리언)
    #           ↓data[:,0]==1, 1 끝나면 data[:,0]==2, ... , data[:,0]==6040
    user_bol = u_id == user # 1
    # 4. 사용자별 정보에서(불리언 인덱싱) 평점만 가져오기
    ratings = data[user_bol][:,2]
    # 5. 평점에서 평균내고
    r_mean = np.mean(ratings)
    # 6. 평균낸 새로운 데이터를 리스트에 담아주기
    list1.append([user, r_mean])
    print('{}번 사용자의 평점 : {}'.format(user, r_mean))

1번 사용자의 평점 : 4.188679245283019
2번 사용자의 평점 : 3.7131782945736433
3번 사용자의 평점 : 3.9019607843137254
4번 사용자의 평점 : 4.190476190476191
5번 사용자의 평점 : 3.1464646464646466
6번 사용자의 평점 : 3.9014084507042255
7번 사용자의 평점 : 4.32258064516129
8번 사용자의 평점 : 3.884892086330935
9번 사용자의 평점 : 3.7358490566037736
10번 사용자의 평점 : 4.114713216957606
11번 사용자의 평점 : 3.2773722627737225
12번 사용자의 평점 : 3.8260869565217392
13번 사용자의 평점 : 3.388888888888889
14번 사용자의 평점 : 3.32
15번 사용자의 평점 : 3.3233830845771144
16번 사용자의 평점 : 3.0285714285714285
17번 사용자의 평점 : 4.075829383886256
18번 사용자의 평점 : 3.6491803278688524
19번 사용자의 평점 : 3.5725490196078433
20번 사용자의 평점 : 4.083333333333333
21번 사용자의 평점 : 2.909090909090909
22번 사용자의 평점 : 3.0673400673400675
23번 사용자의 평점 : 3.3157894736842106
24번 사용자의 평점 : 3.948529411764706
25번 사용자의 평점 : 3.7411764705882353
26번 사용자의 평점 : 2.96
27번 사용자의 평점 : 4.171428571428572
28번 사용자의 평점 : 3.7570093457943927
29번 사용자의 평점 : 3.5833333333333335
30번 사용자의 평점 : 3.488372093023256
31번 사용자의 평점 : 3.73109243697479
32번 사용자의 평점 : 3.625
33번 사용자의 

268번 사용자의 평점 : 3.3946360153256707
269번 사용자의 평점 : 3.8
270번 사용자의 평점 : 4.198412698412699
271번 사용자의 평점 : 3.9583333333333335
272번 사용자의 평점 : 3.6535269709543567
273번 사용자의 평점 : 3.727272727272727
274번 사용자의 평점 : 4.243243243243243
275번 사용자의 평점 : 4.247191011235955
276번 사용자의 평점 : 3.5217391304347827
277번 사용자의 평점 : 3.727272727272727
278번 사용자의 평점 : 3.9646464646464645
279번 사용자의 평점 : 2.872340425531915
280번 사용자의 평점 : 3.94
281번 사용자의 평점 : 3.891891891891892
282번 사용자의 평점 : 3.5172413793103448
283번 사용자의 평점 : 4.962962962962963
284번 사용자의 평점 : 3.021231422505308
285번 사용자의 평점 : 4.16546762589928
286번 사용자의 평점 : 3.883720930232558
287번 사용자의 평점 : 3.70873786407767
288번 사용자의 평점 : 4.589285714285714
289번 사용자의 평점 : 3.9054054054054053
290번 사용자의 평점 : 3.303030303030303
291번 사용자의 평점 : 4.137254901960785
292번 사용자의 평점 : 3.7560975609756095
293번 사용자의 평점 : 3.2460567823343847
294번 사용자의 평점 : 3.489795918367347
295번 사용자의 평점 : 3.764397905759162
296번 사용자의 평점 : 3.597938144329897
297번 사용자의 평점 : 4.0
298번 사용자의 평점 : 3.925925925925926
299번 사용자의 평

571번 사용자의 평점 : 3.7054794520547945
572번 사용자의 평점 : 3.05
573번 사용자의 평점 : 3.9722222222222223
574번 사용자의 평점 : 4.095238095238095
575번 사용자의 평점 : 3.6564417177914113
576번 사용자의 평점 : 3.6666666666666665
577번 사용자의 평점 : 4.487341772151899
578번 사용자의 평점 : 3.9642857142857144
579번 사용자의 평점 : 3.8550724637681157
580번 사용자의 평점 : 3.347826086956522
581번 사용자의 평점 : 3.6666666666666665
582번 사용자의 평점 : 4.282051282051282
583번 사용자의 평점 : 4.040229885057471
584번 사용자의 평점 : 4.2894736842105265
585번 사용자의 평점 : 3.4662162162162162
586번 사용자의 평점 : 4.485714285714286
587번 사용자의 평점 : 3.0077922077922077
588번 사용자의 평점 : 4.057395143487859
589번 사용자의 평점 : 4.0
590번 사용자의 평점 : 4.13855421686747
591번 사용자의 평점 : 3.231404958677686
592번 사용자의 평점 : 4.391304347826087
593번 사용자의 평점 : 3.641509433962264
594번 사용자의 평점 : 4.29559748427673
595번 사용자의 평점 : 3.95
596번 사용자의 평점 : 2.9523809523809526
597번 사용자의 평점 : 4.473684210526316
598번 사용자의 평점 : 3.3157894736842106
599번 사용자의 평점 : 3.8518518518518516
600번 사용자의 평점 : 3.652173913043478
601번 사용자의 평점 : 3.1501340482573728
602번 

854번 사용자의 평점 : 3.027667984189723
855번 사용자의 평점 : 3.4126984126984126
856번 사용자의 평점 : 3.490566037735849
857번 사용자의 평점 : 4.171428571428572
858번 사용자의 평점 : 4.189473684210526
859번 사용자의 평점 : 3.450980392156863
860번 사용자의 평점 : 3.1666666666666665
861번 사용자의 평점 : 3.9375
862번 사용자의 평점 : 3.6724137931034484
863번 사용자의 평점 : 4.225806451612903
864번 사용자의 평점 : 4.050724637681159
865번 사용자의 평점 : 3.8095238095238093
866번 사용자의 평점 : 3.3333333333333335
867번 사용자의 평점 : 3.659090909090909
868번 사용자의 평점 : 3.6
869번 사용자의 평점 : 3.5154394299287413
870번 사용자의 평점 : 3.611111111111111
871번 사용자의 평점 : 3.9069767441860463
872번 사용자의 평점 : 3.635514018691589
873번 사용자의 평점 : 3.8430232558139537
874번 사용자의 평점 : 3.7857142857142856
875번 사용자의 평점 : 4.083333333333333
876번 사용자의 평점 : 3.828828828828829
877번 사용자의 평점 : 3.308056872037915
878번 사용자의 평점 : 4.142857142857143
879번 사용자의 평점 : 4.025
880번 사용자의 평점 : 3.4956521739130433
881번 사용자의 평점 : 2.9354485776805253
882번 사용자의 평점 : 4.0886075949367084
883번 사용자의 평점 : 3.4166666666666665
884번 사용자의 평점 : 4.01010101010101
88

1155번 사용자의 평점 : 3.1923076923076925
1156번 사용자의 평점 : 3.5833333333333335
1157번 사용자의 평점 : 4.2727272727272725
1158번 사용자의 평점 : 3.640625
1159번 사용자의 평점 : 2.56198347107438
1160번 사용자의 평점 : 3.074766355140187
1161번 사용자의 평점 : 3.968421052631579
1162번 사용자의 평점 : 3.551282051282051
1163번 사용자의 평점 : 3.640625
1164번 사용자의 평점 : 3.441048034934498
1165번 사용자의 평점 : 3.574468085106383
1166번 사용자의 평점 : 3.5
1167번 사용자의 평점 : 3.4285714285714284
1168번 사용자의 평점 : 3.4463519313304722
1169번 사용자의 평점 : 2.7711864406779663
1170번 사용자의 평점 : 4.011627906976744
1171번 사용자의 평점 : 4.321428571428571
1172번 사용자의 평점 : 3.5169300225733635
1173번 사용자의 평점 : 3.2493074792243766
1174번 사용자의 평점 : 3.125
1175번 사용자의 평점 : 4.208333333333333
1176번 사용자의 평점 : 4.142857142857143
1177번 사용자의 평점 : 3.9746835443037973
1178번 사용자의 평점 : 3.5
1179번 사용자의 평점 : 3.6623931623931623
1180번 사용자의 평점 : 4.45945945945946
1181번 사용자의 평점 : 2.815910585141354
1182번 사용자의 평점 : 3.357142857142857
1183번 사용자의 평점 : 3.682795698924731
1184번 사용자의 평점 : 3.338129496402878
1185번 사용자의 평점 : 3.644444444444

1409번 사용자의 평점 : 4.214285714285714
1410번 사용자의 평점 : 4.064102564102564
1411번 사용자의 평점 : 3.566666666666667
1412번 사용자의 평점 : 3.3333333333333335
1413번 사용자의 평점 : 3.8324324324324324
1414번 사용자의 평점 : 3.7837837837837838
1415번 사용자의 평점 : 3.7150837988826817
1416번 사용자의 평점 : 3.5454545454545454
1417번 사용자의 평점 : 3.413793103448276
1418번 사용자의 평점 : 2.9510489510489513
1419번 사용자의 평점 : 2.6470588235294117
1420번 사용자의 평점 : 3.7311827956989245
1421번 사용자의 평점 : 3.758974358974359
1422번 사용자의 평점 : 3.0123626373626373
1423번 사용자의 평점 : 4.1875
1424번 사용자의 평점 : 3.409090909090909
1425번 사용자의 평점 : 3.647814910025707
1426번 사용자의 평점 : 3.494764397905759
1427번 사용자의 평점 : 3.6470588235294117
1428번 사용자의 평점 : 4.211538461538462
1429번 사용자의 평점 : 3.2916666666666665
1430번 사용자의 평점 : 4.163793103448276
1431번 사용자의 평점 : 3.380952380952381
1432번 사용자의 평점 : 3.5428571428571427
1433번 사용자의 평점 : 3.337078651685393
1434번 사용자의 평점 : 2.4050179211469533
1435번 사용자의 평점 : 3.4571428571428573
1436번 사용자의 평점 : 3.9696969696969697
1437번 사용자의 평점 : 4.541935483870968
1438번 사용자의

1685번 사용자의 평점 : 3.574418604651163
1686번 사용자의 평점 : 3.5357142857142856
1687번 사용자의 평점 : 3.5318066157760812
1688번 사용자의 평점 : 3.5757575757575757
1689번 사용자의 평점 : 3.609375
1690번 사용자의 평점 : 3.5167785234899327
1691번 사용자의 평점 : 3.52
1692번 사용자의 평점 : 4.478260869565218
1693번 사용자의 평점 : 3.7419354838709675
1694번 사용자의 평점 : 3.741206030150754
1695번 사용자의 평점 : 3.6530612244897958
1696번 사용자의 평점 : 3.621019108280255
1697번 사용자의 평점 : 4.18361581920904
1698번 사용자의 평점 : 3.9310344827586206
1699번 사용자의 평점 : 4.313218390804598
1700번 사용자의 평점 : 3.533333333333333
1701번 사용자의 평점 : 3.5543478260869565
1702번 사용자의 평점 : 4.55
1703번 사용자의 평점 : 4.076923076923077
1704번 사용자의 평점 : 4.194444444444445
1705번 사용자의 평점 : 3.6941176470588237
1706번 사용자의 평점 : 3.8
1707번 사용자의 평점 : 4.329545454545454
1708번 사용자의 평점 : 3.8636363636363638
1709번 사용자의 평점 : 3.704761904761905
1710번 사용자의 평점 : 3.6582278481012658
1711번 사용자의 평점 : 3.6206896551724137
1712번 사용자의 평점 : 3.512720156555773
1713번 사용자의 평점 : 3.3333333333333335
1714번 사용자의 평점 : 3.510948905109489
1715번 사용자의 평점 : 3

1961번 사용자의 평점 : 3.550561797752809
1962번 사용자의 평점 : 2.6679174484052535
1963번 사용자의 평점 : 4.180722891566265
1964번 사용자의 평점 : 3.6363636363636362
1965번 사용자의 평점 : 3.125
1966번 사용자의 평점 : 4.363636363636363
1967번 사용자의 평점 : 3.5416666666666665
1968번 사용자의 평점 : 2.7612612612612613
1969번 사용자의 평점 : 3.816247582205029
1970번 사용자의 평점 : 3.576923076923077
1971번 사용자의 평점 : 4.2727272727272725
1972번 사용자의 평점 : 4.409638554216867
1973번 사용자의 평점 : 3.8421052631578947
1974번 사용자의 평점 : 3.7644787644787643
1975번 사용자의 평점 : 3.836734693877551
1976번 사용자의 평점 : 3.886178861788618
1977번 사용자의 평점 : 3.626865671641791
1978번 사용자의 평점 : 3.4675324675324677
1979번 사용자의 평점 : 3.1142857142857143
1980번 사용자의 평점 : 3.4825396825396826
1981번 사용자의 평점 : 3.029850746268657
1982번 사용자의 평점 : 3.425806451612903
1983번 사용자의 평점 : 4.142857142857143
1984번 사용자의 평점 : 3.5653710247349824
1985번 사용자의 평점 : 3.575
1986번 사용자의 평점 : 4.590909090909091
1987번 사용자의 평점 : 3.617021276595745
1988번 사용자의 평점 : 3.5230524642289347
1989번 사용자의 평점 : 3.3333333333333335
1990번 사용자의 평점 : 3.8571428

2255번 사용자의 평점 : 3.6685714285714286
2256번 사용자의 평점 : 4.0
2257번 사용자의 평점 : 3.5428571428571427
2258번 사용자의 평점 : 3.446927374301676
2259번 사용자의 평점 : 4.471615720524017
2260번 사용자의 평점 : 3.64
2261번 사용자의 평점 : 3.396694214876033
2262번 사용자의 평점 : 3.6842105263157894
2263번 사용자의 평점 : 3.707627118644068
2264번 사용자의 평점 : 3.63
2265번 사용자의 평점 : 3.6422413793103448
2266번 사용자의 평점 : 4.0495049504950495
2267번 사용자의 평점 : 3.547169811320755
2268번 사용자의 평점 : 4.260869565217392
2269번 사용자의 평점 : 3.36
2270번 사용자의 평점 : 3.4466019417475726
2271번 사용자의 평점 : 4.112462006079028
2272번 사용자의 평점 : 3.921259842519685
2273번 사용자의 평점 : 3.8450704225352115
2274번 사용자의 평점 : 3.775
2275번 사용자의 평점 : 3.864864864864865
2276번 사용자의 평점 : 4.324074074074074
2277번 사용자의 평점 : 3.392857142857143
2278번 사용자의 평점 : 3.417910447761194
2279번 사용자의 평점 : 3.638095238095238
2280번 사용자의 평점 : 4.105263157894737
2281번 사용자의 평점 : 4.0519480519480515
2282번 사용자의 평점 : 4.026595744680851
2283번 사용자의 평점 : 3.697674418604651
2284번 사용자의 평점 : 3.8846153846153846
2285번 사용자의 평점 : 3.6346153846153846
2

2526번 사용자의 평점 : 3.88212927756654
2527번 사용자의 평점 : 4.142857142857143
2528번 사용자의 평점 : 3.2419354838709675
2529번 사용자의 평점 : 3.6933497536945814
2530번 사용자의 평점 : 3.85
2531번 사용자의 평점 : 3.806451612903226
2532번 사용자의 평점 : 4.096774193548387
2533번 사용자의 평점 : 3.9236641221374047
2534번 사용자의 평점 : 3.473684210526316
2535번 사용자의 평점 : 3.984848484848485
2536번 사용자의 평점 : 3.1578947368421053
2537번 사용자의 평점 : 3.027075812274368
2538번 사용자의 평점 : 3.88
2539번 사용자의 평점 : 3.8048780487804876
2540번 사용자의 평점 : 3.968609865470852
2541번 사용자의 평점 : 3.31640625
2542번 사용자의 평점 : 3.88
2543번 사용자의 평점 : 4.458333333333333
2544번 사용자의 평점 : 3.689986282578875
2545번 사용자의 평점 : 4.098039215686274
2546번 사용자의 평점 : 3.3220338983050848
2547번 사용자의 평점 : 4.143884892086331
2548번 사용자의 평점 : 3.9302325581395348
2549번 사용자의 평점 : 3.0869565217391304
2550번 사용자의 평점 : 3.702127659574468
2551번 사용자의 평점 : 3.3026315789473686
2552번 사용자의 평점 : 3.625
2553번 사용자의 평점 : 4.130434782608695
2554번 사용자의 평점 : 4.023809523809524
2555번 사용자의 평점 : 3.6012658227848102
2556번 사용자의 평점 : 3.48936170212

2802번 사용자의 평점 : 3.6
2803번 사용자의 평점 : 3.7927927927927927
2804번 사용자의 평점 : 3.888888888888889
2805번 사용자의 평점 : 3.897727272727273
2806번 사용자의 평점 : 3.3037974683544302
2807번 사용자의 평점 : 3.391044776119403
2808번 사용자의 평점 : 4.115107913669065
2809번 사용자의 평점 : 4.339449541284404
2810번 사용자의 평점 : 3.4688279301745637
2811번 사용자의 평점 : 3.6666666666666665
2812번 사용자의 평점 : 3.603305785123967
2813번 사용자의 평점 : 3.0
2814번 사용자의 평점 : 4.047058823529412
2815번 사용자의 평점 : 3.690909090909091
2816번 사용자의 평점 : 3.8181818181818183
2817번 사용자의 평점 : 4.2073170731707314
2818번 사용자의 평점 : 3.6109215017064846
2819번 사용자의 평점 : 3.9
2820번 사용자의 평점 : 2.9642058165548097
2821번 사용자의 평점 : 3.6333333333333333
2822번 사용자의 평점 : 3.725806451612903
2823번 사용자의 평점 : 2.9148936170212765
2824번 사용자의 평점 : 3.9274193548387095
2825번 사용자의 평점 : 3.9592760180995477
2826번 사용자의 평점 : 3.609848484848485
2827번 사용자의 평점 : 3.242424242424242
2828번 사용자의 평점 : 4.017241379310345
2829번 사용자의 평점 : 2.9473684210526314
2830번 사용자의 평점 : 3.388235294117647
2831번 사용자의 평점 : 4.222222222222222
2832번 사용자

3093번 사용자의 평점 : 3.798882681564246
3094번 사용자의 평점 : 3.658536585365854
3095번 사용자의 평점 : 3.896551724137931
3096번 사용자의 평점 : 4.106598984771574
3097번 사용자의 평점 : 3.634920634920635
3098번 사용자의 평점 : 3.369565217391304
3099번 사용자의 평점 : 3.2830188679245285
3100번 사용자의 평점 : 4.2
3101번 사용자의 평점 : 4.148148148148148
3102번 사용자의 평점 : 3.4411764705882355
3103번 사용자의 평점 : 4.128205128205129
3104번 사용자의 평점 : 3.896551724137931
3105번 사용자의 평점 : 3.9916666666666667
3106번 사용자의 평점 : 4.161764705882353
3107번 사용자의 평점 : 3.5555555555555554
3108번 사용자의 평점 : 3.68801652892562
3109번 사용자의 평점 : 3.526315789473684
3110번 사용자의 평점 : 3.6033333333333335
3111번 사용자의 평점 : 3.2419354838709675
3112번 사용자의 평점 : 3.3896713615023475
3113번 사용자의 평점 : 3.68
3114번 사용자의 평점 : 3.342857142857143
3115번 사용자의 평점 : 3.4166666666666665
3116번 사용자의 평점 : 3.635294117647059
3117번 사용자의 평점 : 4.297297297297297
3118번 사용자의 평점 : 3.543859649122807
3119번 사용자의 평점 : 3.3777777777777778
3120번 사용자의 평점 : 3.6216216216216215
3121번 사용자의 평점 : 3.4686346863468636
3122번 사용자의 평점 : 3.1111111111111

3371번 사용자의 평점 : 3.43064182194617
3372번 사용자의 평점 : 4.258064516129032
3373번 사용자의 평점 : 3.5
3374번 사용자의 평점 : 3.9326923076923075
3375번 사용자의 평점 : 3.740740740740741
3376번 사용자의 평점 : 3.35
3377번 사용자의 평점 : 3.982142857142857
3378번 사용자의 평점 : 3.578723404255319
3379번 사용자의 평점 : 3.717948717948718
3380번 사용자의 평점 : 3.752759381898455
3381번 사용자의 평점 : 3.4827586206896552
3382번 사용자의 평점 : 3.392857142857143
3383번 사용자의 평점 : 3.607843137254902
3384번 사용자의 평점 : 3.5714285714285716
3385번 사용자의 평점 : 3.3333333333333335
3386번 사용자의 평점 : 3.7094594594594597
3387번 사용자의 평점 : 3.3795620437956204
3388번 사용자의 평점 : 3.6666666666666665
3389번 사용자의 평점 : 2.826923076923077
3390번 사용자의 평점 : 4.187192118226601
3391번 사용자의 평점 : 3.7203947368421053
3392번 사용자의 평점 : 3.8
3393번 사용자의 평점 : 3.5430711610486894
3394번 사용자의 평점 : 3.892638036809816
3395번 사용자의 평점 : 3.6964285714285716
3396번 사용자의 평점 : 3.8260869565217392
3397번 사용자의 평점 : 4.068965517241379
3398번 사용자의 평점 : 3.6
3399번 사용자의 평점 : 3.5454545454545454
3400번 사용자의 평점 : 4.059633027522936
3401번 사용자의 평점 : 2.952210

3657번 사용자의 평점 : 4.157894736842105
3658번 사용자의 평점 : 3.981203007518797
3659번 사용자의 평점 : 4.21875
3660번 사용자의 평점 : 3.7413793103448274
3661번 사용자의 평점 : 3.92
3662번 사용자의 평점 : 3.034090909090909
3663번 사용자의 평점 : 3.4505494505494507
3664번 사용자의 평점 : 3.029850746268657
3665번 사용자의 평점 : 3.8564814814814814
3666번 사용자의 평점 : 4.142857142857143
3667번 사용자의 평점 : 3.9272727272727272
3668번 사용자의 평점 : 3.973684210526316
3669번 사용자의 평점 : 3.194954128440367
3670번 사용자의 평점 : 3.573529411764706
3671번 사용자의 평점 : 4.201923076923077
3672번 사용자의 평점 : 3.3201970443349755
3673번 사용자의 평점 : 3.8962264150943398
3674번 사용자의 평점 : 3.7472527472527473
3675번 사용자의 평점 : 3.487632508833922
3676번 사용자의 평점 : 3.633663366336634
3677번 사용자의 평점 : 3.950354609929078
3678번 사용자의 평점 : 3.2014388489208634
3679번 사용자의 평점 : 3.5625
3680번 사용자의 평점 : 3.892857142857143
3681번 사용자의 평점 : 3.874251497005988
3682번 사용자의 평점 : 4.461538461538462
3683번 사용자의 평점 : 3.095076400679117
3684번 사용자의 평점 : 4.280575539568345
3685번 사용자의 평점 : 4.068403908794788
3686번 사용자의 평점 : 4.4
3687번 사용자의 평점 : 3.07

3933번 사용자의 평점 : 3.875
3934번 사용자의 평점 : 2.607396870554765
3935번 사용자의 평점 : 3.4226190476190474
3936번 사용자의 평점 : 4.352941176470588
3937번 사용자의 평점 : 4.273972602739726
3938번 사용자의 평점 : 4.170212765957447
3939번 사용자의 평점 : 3.7083333333333335
3940번 사용자의 평점 : 3.680894308943089
3941번 사용자의 평점 : 3.02
3942번 사용자의 평점 : 2.655115511551155
3943번 사용자의 평점 : 4.2153846153846155
3944번 사용자의 평점 : 3.54
3945번 사용자의 평점 : 3.4237288135593222
3946번 사용자의 평점 : 3.734848484848485
3947번 사용자의 평점 : 4.117647058823529
3948번 사용자의 평점 : 3.372549019607843
3949번 사용자의 평점 : 3.824324324324324
3950번 사용자의 평점 : 3.2714285714285714
3951번 사용자의 평점 : 3.5969387755102042
3952번 사용자의 평점 : 3.896551724137931
3953번 사용자의 평점 : 3.6153846153846154
3954번 사용자의 평점 : 3.441860465116279
3955번 사용자의 평점 : 3.4407894736842106
3956번 사용자의 평점 : 3.909090909090909
3957번 사용자의 평점 : 3.883190883190883
3958번 사용자의 평점 : 3.6402439024390243
3959번 사용자의 평점 : 2.64
3960번 사용자의 평점 : 4.178571428571429
3961번 사용자의 평점 : 3.4956521739130433
3962번 사용자의 평점 : 3.4714285714285715
3963번 사용자의 평점 : 4.02

4207번 사용자의 평점 : 4.246963562753036
4208번 사용자의 평점 : 4.0625
4209번 사용자의 평점 : 3.608695652173913
4210번 사용자의 평점 : 3.717557251908397
4211번 사용자의 평점 : 2.9583333333333335
4212번 사용자의 평점 : 3.7096774193548385
4213번 사용자의 평점 : 4.060759493670886
4214번 사용자의 평점 : 3.871794871794872
4215번 사용자의 평점 : 4.003460207612457
4216번 사용자의 평점 : 4.074074074074074
4217번 사용자의 평점 : 4.01038961038961
4218번 사용자의 평점 : 3.5544554455445545
4219번 사용자의 평점 : 3.7837837837837838
4220번 사용자의 평점 : 3.5201612903225805
4221번 사용자의 평점 : 4.146067415730337
4222번 사용자의 평점 : 3.9508196721311477
4223번 사용자의 평점 : 3.3496932515337425
4224번 사용자의 평점 : 3.8724035608308607
4225번 사용자의 평점 : 3.6589147286821704
4226번 사용자의 평점 : 3.7837837837837838
4227번 사용자의 평점 : 2.7013093289689034
4228번 사용자의 평점 : 3.652173913043478
4229번 사용자의 평점 : 3.634920634920635
4230번 사용자의 평점 : 3.9523809523809526
4231번 사용자의 평점 : 3.42
4232번 사용자의 평점 : 3.826923076923077
4233번 사용자의 평점 : 3.7611940298507465
4234번 사용자의 평점 : 3.8867924528301887
4235번 사용자의 평점 : 3.7698412698412698
4236번 사용자의 평점 : 4.098039

4496번 사용자의 평점 : 3.8225806451612905
4497번 사용자의 평점 : 3.778
4498번 사용자의 평점 : 3.0714285714285716
4499번 사용자의 평점 : 4.030612244897959
4500번 사용자의 평점 : 2.9642857142857144
4501번 사용자의 평점 : 3.9722222222222223
4502번 사용자의 평점 : 3.8950617283950617
4503번 사용자의 평점 : 4.157894736842105
4504번 사용자의 평점 : 4.12
4505번 사용자의 평점 : 4.207885304659499
4506번 사용자의 평점 : 3.9608208955223883
4507번 사용자의 평점 : 4.366379310344827
4508번 사용자의 평점 : 3.0767960363336084
4509번 사용자의 평점 : 3.919047619047619
4510번 사용자의 평점 : 2.8379032258064516
4511번 사용자의 평점 : 4.183673469387755
4512번 사용자의 평점 : 3.861635220125786
4513번 사용자의 평점 : 3.7714285714285714
4514번 사용자의 평점 : 3.3741496598639458
4515번 사용자의 평점 : 4.409090909090909
4516번 사용자의 평점 : 4.381818181818182
4517번 사용자의 평점 : 3.0653753026634383
4518번 사용자의 평점 : 4.5476190476190474
4519번 사용자의 평점 : 3.6666666666666665
4520번 사용자의 평점 : 3.7719298245614037
4521번 사용자의 평점 : 3.8034934497816595
4522번 사용자의 평점 : 3.4021164021164023
4523번 사용자의 평점 : 3.4593908629441623
4524번 사용자의 평점 : 3.3044982698961936
4525번 사용자의 평점 : 3.95


4769번 사용자의 평점 : 3.353846153846154
4770번 사용자의 평점 : 3.6666666666666665
4771번 사용자의 평점 : 3.7582846003898633
4772번 사용자의 평점 : 4.12
4773번 사용자의 평점 : 4.145631067961165
4774번 사용자의 평점 : 4.283505154639175
4775번 사용자의 평점 : 3.4
4776번 사용자의 평점 : 4.4
4777번 사용자의 평점 : 3.972972972972973
4778번 사용자의 평점 : 4.25
4779번 사용자의 평점 : 4.197183098591549
4780번 사용자의 평점 : 4.1909090909090905
4781번 사용자의 평점 : 3.9767441860465116
4782번 사용자의 평점 : 3.700854700854701
4783번 사용자의 평점 : 3.709090909090909
4784번 사용자의 평점 : 4.034229828850855
4785번 사용자의 평점 : 4.018450184501845
4786번 사용자의 평점 : 3.8
4787번 사용자의 평점 : 3.066666666666667
4788번 사용자의 평점 : 3.363036303630363
4789번 사용자의 평점 : 3.4814814814814814
4790번 사용자의 평점 : 3.394179894179894
4791번 사용자의 평점 : 3.176
4792번 사용자의 평점 : 3.8
4793번 사용자의 평점 : 3.1560693641618496
4794번 사용자의 평점 : 4.294117647058823
4795번 사용자의 평점 : 4.068965517241379
4796번 사용자의 평점 : 3.6099706744868034
4797번 사용자의 평점 : 4.017543859649122
4798번 사용자의 평점 : 3.411764705882353
4799번 사용자의 평점 : 3.7413793103448274
4800번 사용자의 평점 : 3.27667984189723

5043번 사용자의 평점 : 4.2
5044번 사용자의 평점 : 4.087591240875913
5045번 사용자의 평점 : 3.176470588235294
5046번 사용자의 평점 : 3.6497695852534564
5047번 사용자의 평점 : 3.523510971786834
5048번 사용자의 평점 : 4.382022471910112
5049번 사용자의 평점 : 4.046875
5050번 사용자의 평점 : 3.988235294117647
5051번 사용자의 평점 : 3.7333333333333334
5052번 사용자의 평점 : 4.190476190476191
5053번 사용자의 평점 : 3.8225108225108224
5054번 사용자의 평점 : 3.3384615384615386
5055번 사용자의 평점 : 3.6904761904761907
5056번 사용자의 평점 : 4.479381443298969
5057번 사용자의 평점 : 3.554054054054054
5058번 사용자의 평점 : 4.340425531914893
5059번 사용자의 평점 : 3.5588235294117645
5060번 사용자의 평점 : 4.0
5061번 사용자의 평점 : 3.6492890995260665
5062번 사용자의 평점 : 4.208333333333333
5063번 사용자의 평점 : 3.849557522123894
5064번 사용자의 평점 : 4.070707070707071
5065번 사용자의 평점 : 3.6830188679245284
5066번 사용자의 평점 : 4.121212121212121
5067번 사용자의 평점 : 4.142857142857143
5068번 사용자의 평점 : 4.054545454545455
5069번 사용자의 평점 : 4.76
5070번 사용자의 평점 : 3.5471311475409837
5071번 사용자의 평점 : 4.1234567901234565
5072번 사용자의 평점 : 4.271186440677966
5073번 사용자의 평점 : 4.52

5334번 사용자의 평점 : 1.9272727272727272
5335번 사용자의 평점 : 3.9683544303797467
5336번 사용자의 평점 : 4.382978723404255
5337번 사용자의 평점 : 4.214689265536723
5338번 사용자의 평점 : 3.798076923076923
5339번 사용자의 평점 : 3.7777777777777777
5340번 사용자의 평점 : 3.616822429906542
5341번 사용자의 평점 : 3.6587301587301586
5342번 사용자의 평점 : 3.767857142857143
5343번 사용자의 평점 : 4.638888888888889
5344번 사용자의 평점 : 3.6142131979695433
5345번 사용자의 평점 : 3.6426426426426426
5346번 사용자의 평점 : 3.925925925925926
5347번 사용자의 평점 : 3.129277566539924
5348번 사용자의 평점 : 3.44
5349번 사용자의 평점 : 4.058091286307054
5350번 사용자의 평점 : 2.9269406392694064
5351번 사용자의 평점 : 3.8846153846153846
5352번 사용자의 평점 : 3.7135922330097086
5353번 사용자의 평점 : 3.7966101694915255
5354번 사용자의 평점 : 3.6739130434782608
5355번 사용자의 평점 : 3.6187845303867405
5356번 사용자의 평점 : 3.4878048780487805
5357번 사용자의 평점 : 3.875
5358번 사용자의 평점 : 4.04
5359번 사용자의 평점 : 3.7019607843137257
5360번 사용자의 평점 : 3.4473684210526314
5361번 사용자의 평점 : 3.620320855614973
5362번 사용자의 평점 : 3.0869565217391304
5363번 사용자의 평점 : 4.344262295081967
53

5607번 사용자의 평점 : 3.52027027027027
5608번 사용자의 평점 : 3.75
5609번 사용자의 평점 : 4.675
5610번 사용자의 평점 : 4.2
5611번 사용자의 평점 : 4.258064516129032
5612번 사용자의 평점 : 2.9722222222222223
5613번 사용자의 평점 : 3.63953488372093
5614번 사용자의 평점 : 3.805256869772999
5615번 사용자의 평점 : 3.4602649006622515
5616번 사용자의 평점 : 3.853846153846154
5617번 사용자의 평점 : 3.5405405405405403
5618번 사용자의 평점 : 3.8979591836734695
5619번 사용자의 평점 : 3.652173913043478
5620번 사용자의 평점 : 3.4246575342465753
5621번 사용자의 평점 : 3.0251572327044025
5622번 사용자의 평점 : 4.127906976744186
5623번 사용자의 평점 : 3.9015151515151514
5624번 사용자의 평점 : 3.3529411764705883
5625번 사용자의 평점 : 3.9078947368421053
5626번 사용자의 평점 : 4.38728323699422
5627번 사용자의 평점 : 2.996319018404908
5628번 사용자의 평점 : 3.4347826086956523
5629번 사용자의 평점 : 4.475247524752476
5630번 사용자의 평점 : 4.2091254752851714
5631번 사용자의 평점 : 4.177215189873418
5632번 사용자의 평점 : 3.65
5633번 사용자의 평점 : 3.8205128205128207
5634번 사용자의 평점 : 3.73
5635번 사용자의 평점 : 3.5833333333333335
5636번 사용자의 평점 : 3.1580188679245285
5637번 사용자의 평점 : 3.9347826086956523

5886번 사용자의 평점 : 3.2708757637474544
5887번 사용자의 평점 : 3.6463414634146343
5888번 사용자의 평점 : 3.1831442463533226
5889번 사용자의 평점 : 3.9076923076923076
5890번 사용자의 평점 : 3.911854103343465
5891번 사용자의 평점 : 3.6666666666666665
5892번 사용자의 평점 : 4.087719298245614
5893번 사용자의 평점 : 3.168918918918919
5894번 사용자의 평점 : 3.8956521739130436
5895번 사용자의 평점 : 3.5
5896번 사용자의 평점 : 2.5528846153846154
5897번 사용자의 평점 : 3.8867924528301887
5898번 사용자의 평점 : 3.7586206896551726
5899번 사용자의 평점 : 3.380952380952381
5900번 사용자의 평점 : 3.296
5901번 사용자의 평점 : 3.2
5902번 사용자의 평점 : 3.632183908045977
5903번 사용자의 평점 : 3.7662337662337664
5904번 사용자의 평점 : 3.5
5905번 사용자의 평점 : 3.638157894736842
5906번 사용자의 평점 : 3.9193548387096775
5907번 사용자의 평점 : 3.8541666666666665
5908번 사용자의 평점 : 4.121359223300971
5909번 사용자의 평점 : 3.2758620689655173
5910번 사용자의 평점 : 3.7846153846153845
5911번 사용자의 평점 : 3.8362573099415203
5912번 사용자의 평점 : 3.592
5913번 사용자의 평점 : 3.8701298701298703
5914번 사용자의 평점 : 3.942857142857143
5915번 사용자의 평점 : 3.6888111888111887
5916번 사용자의 평점 : 3.16903409090

In [45]:
# 간단하게 코드를 줄여보자!
user_id = np.unique(data[:,0])
list3 = []

for user in user_id:
    user_mean = data[data[:,0]==user, 2].mean()
    list3.append([user, user_mean])
    # 리스트에 담기 [사용자 아이디, 사용자 아이디에 따른 평점 평균]

In [46]:
list3

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

In [47]:
# 파일을 외부로 내보낼 때 쓰는 함수
# np.savetxt('파일명.확장자', 해당 array 변수, 구분자)
np.savetxt('user_id_mean.csv',list3,delimiter=',')
# 이 때 저장되는 파일 경로는 해당 notebook이 있는 위치폴더